apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - image: 183295435445.dkr.ecr.ap-south-1.amazonaws.com/voting-app/vote:latest
          name: vote
          ports:
            - containerPort: 80
              name: vote
