apiVersion: v1
kind: Pod
metadata: 
  name: basic-react
  labels:
    app: basic-react
spec: 
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: basic-react
      image: 183295435445.dkr.ecr.ap-south-1.amazonaws.com/abhinav/basic-react:latest
      ports:
        - containerPort: 5173
