apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: 183295435445.dkr.ecr.ap-south-1.amazonaws.com/voting-app/result:latest
          name: result
          ports:
            - containerPort: 80
              name: result 