apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: 183295435445.dkr.ecr.ap-south-1.amazonaws.com/voting-app/worker:latest
          name: worker
  
